[package]
name = "ntex-test"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12.1"
ntex = { version = "2.0.1", features = ["tokio"] }
diesel = { version = "*", features = ["sqlite"] }
serde = { version = "1.0.203", features = ["derive"] } 
serde_json = "1.0.117"
